apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: cielojem/my_db:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 3306
