apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-app
spec:
  containers:
    - name: web-app-container
      image: cielojem/my_app
      env:
        - name: BACKGROUND_COLOR
          value: blue
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      ports:
        - containerPort: 8080
