name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  # Optional. Remove this line if you don't use session tokens.

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-ecr: true

      - name: Verify directory contents
        run: ls -la .

      - name: Build and push Image 1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: 439896484708.dkr.ecr.us-east-1.amazonaws.com/flask-app-repo:latest  # Adjusted to use your account ID and repo name.

      - name: Build and push Image 2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_mysql
          push: true
          tags: 439896484708.dkr.ecr.us-east-1.amazonaws.com/flask-app-repo:mysql  # Adjusted to use your account ID, repo name, and a different tag for the MySQL image.
